In [6]:
import keras
from keras.models import Sequential

In [2]:
# Basic kind of model: Sequential
model = Sequential()

In [3]:
# Basic kind of layer: fully connected layer
from keras.layers import Dense

model.add(Dense(units=64, activation='relu', input_dim=100))
model.add(Dense(units=10, activation='softmax'))

In [4]:
# Must compile model
model.compile(loss='categorical_crossentropy',
              optimizer='sgd',
              metrics=['accuracy'])

In [7]:
# More advanced compiling
model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.SGD(lr=0.01, momentum=0.9, nesterov=True))

## Sequential API

In [8]:
from keras.models import Sequential
from keras.layers import Dense, Activation

In [12]:
# Creating a model: Method #1:
# Note: only first layer needs "input_shape"

model = Sequential([
    Dense(32, input_shape=(784,)),
    Activation('relu'),
    Dense(10),
    Activation('softmax'),
])

In [11]:
# Creating a model: Method #2:

model = Sequential()
model.add(Dense(32, input_dim=784))
model.add(Activation('relu'))

In [13]:
# Compiling:
# compile always takes three arguments:
# 1. optimizer
# 2. loss
# 3. metrics

# e.g. for multiclass classification:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

### Data preprocessing

Keras expects Numpy arrays:

In [35]:
# Binary classification example:

import numpy as np
data = np.random.random((1000, 100))
labels = np.random.randint(2, size=(1000, 1)) # Labels are either 0 or 1

binary_model = Sequential()
binary_model.add(Dense(32, activation='relu', input_dim=100))
binary_model.add(Dense(1, activation='sigmoid'))
binary_model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# Train the model, iterating on the data in batches of 32 samples
binary_model.fit(data, labels, epochs=10, batch_size=32)

Epoch 1/10
1000/1000 [==============================] - 0s 439us/step - loss: 0.6987 - acc: 0.5300
Epoch 2/10
1000/1000 [==============================] - 0s 65us/step - loss: 0.6917 - acc: 0.5170
Epoch 3/10
1000/1000 [==============================] - 0s 89us/step - loss: 0.6857 - acc: 0.5500
Epoch 4/10
1000/1000 [==============================] - 0s 67us/step - loss: 0.6825 - acc: 0.5650
Epoch 5/10
1000/1000 [==============================] - 0s 60us/step - loss: 0.6776 - acc: 0.5790
Epoch 6/10
1000/1000 [==============================] - 0s 57us/step - loss: 0.6742 - acc: 0.5800
Epoch 7/10
1000/1000 [==============================] - 0s 65us/step - loss: 0.6722 - acc: 0.5930
Epoch 8/10
1000/1000 [==============================] - 0s 58us/step - loss: 0.6721 - acc: 0.5690
Epoch 9/10
1000/1000 [==============================] - 0s 65us/step - loss: 0.6641 - acc: 0.5980
Epoch 10/10
1000/1000 [==============================] - 0s 71us/step - loss: 0.6621 - acc: 0.6050


In [36]:
num_rows = 3
print(binary_model.predict(data[:num_rows, :])) # predictions for first n rows
print(binary_model.predict(data[:num_rows, :], verbose=1)) # verbose = 1: shows timing
print(binary_model.predict(data[:num_rows, :]).shape) # n rows, 1 column, since loss is _binary_ CE
print(labels[:num_rows, :]) # first 10 labels
print(binary_model.predict_classes(data[:num_rows, :])) # > or less than 0.5

[[0.45106348]
 [0.3374913 ]
 [0.43661577]]
3/3 [==============================] - 0s 322us/step
[[0.45106348]
 [0.3374913 ]
 [0.43661577]]
(3, 1)
[[1]
 [1]
 [0]]
[[0]
 [0]
 [0]]


In [42]:
# For a single-input model with 10 classes (categorical classification):

categorical_model = Sequential()
categorical_model.add(Dense(32, activation='relu', input_dim=100))
categorical_model.add(Dense(10, activation='softmax'))
categorical_model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Generate dummy data
import numpy as np
data = np.random.random((1000, 100))
labels = np.random.randint(10, size=(1000, 1))

print(labels[:3, :]) # first 3 labels

[[0]
 [5]
 [5]]


In [40]:
# Convert labels to categorical one-hot encoding
one_hot_labels = keras.utils.to_categorical(labels, num_classes=10)

print(one_hot_labels[:3, :]) # one hot - it works!

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [43]:
# Train the model, iterating on the data in batches of 32 samples
categorical_model.fit(data, one_hot_labels, epochs=10, batch_size=32);

Epoch 1/10
1000/1000 [==============================] - 0s 485us/step - loss: 2.3574 - acc: 0.0990
Epoch 2/10
1000/1000 [==============================] - 0s 80us/step - loss: 2.3111 - acc: 0.1170
Epoch 3/10
1000/1000 [==============================] - 0s 66us/step - loss: 2.2957 - acc: 0.1220
Epoch 4/10
1000/1000 [==============================] - 0s 69us/step - loss: 2.2855 - acc: 0.1320
Epoch 5/10
1000/1000 [==============================] - 0s 69us/step - loss: 2.2748 - acc: 0.1430
Epoch 6/10
1000/1000 [==============================] - 0s 69us/step - loss: 2.2650 - acc: 0.1480
Epoch 7/10
1000/1000 [==============================] - 0s 70us/step - loss: 2.2574 - acc: 0.1550
Epoch 8/10
1000/1000 [==============================] - 0s 75us/step - loss: 2.2474 - acc: 0.1670
Epoch 9/10
1000/1000 [==============================] - 0s 60us/step - loss: 2.2373 - acc: 0.1720
Epoch 10/10
1000/1000 [==============================] - 0s 57us/step - loss: 2.2275 - acc: 0.1710


In [44]:
num_rows = 3
print(categorical_model.predict(data[:num_rows, :])) # predictions for first n rows
print(categorical_model.predict(data[:num_rows, :], verbose=1)) # verbose = 1: shows timing
print(categorical_model.predict(data[:num_rows, :]).shape) # n rows, 1 column, since loss is _binary_ CE
print(labels[:num_rows, :]) # first 10 labels
print(categorical_model.predict_classes(data[:num_rows, :])) # > or less than 0.5

[[0.16144872 0.07992745 0.07732411 0.12636654 0.09389471 0.10945417
  0.07913879 0.09076368 0.10343998 0.07824185]
 [0.11248828 0.06741264 0.16594337 0.04644856 0.15298468 0.05377607
  0.09432892 0.0687197  0.17357887 0.06431896]
 [0.08553436 0.06892415 0.1275761  0.09413425 0.08785402 0.09666151
  0.08375759 0.11947548 0.14359014 0.09249242]]
3/3 [==============================] - 0s 334us/step
[[0.16144872 0.07992745 0.07732411 0.12636654 0.09389471 0.10945417
  0.07913879 0.09076368 0.10343998 0.07824185]
 [0.11248828 0.06741264 0.16594337 0.04644856 0.15298468 0.05377607
  0.09432892 0.0687197  0.17357887 0.06431896]
 [0.08553436 0.06892415 0.1275761  0.09413425 0.08785402 0.09666151
  0.08375759 0.11947548 0.14359014 0.09249242]]
(3, 10)
[[0]
 [5]
 [5]]
[0 8 8]


## Convolutional network

### Data preprocessing

In [45]:
import numpy as np
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.optimizers import SGD

# Generate dummy data
# 100 "data points", 100 x 100 images, 3 channels
x_train = np.random.random((100, 100, 100, 3)) 

# one hot encoded 10 class labels, as above
y_train = keras.utils.to_categorical(np.random.randint(10, size=(100, 1)), num_classes=10)  

# 20 "data points", 100 x 100 images, 3 channels
x_test = np.random.random((20, 100, 100, 3))

# one hot encoded 10 class labels, as above
y_test = keras.utils.to_categorical(np.random.randint(10, size=(20, 1)), num_classes=10)

### Convolutional architecture

In [46]:
model = Sequential()
# input: 100x100 images with 3 channels -> (100, 100, 3) tensors.
# this applies 32 convolution filters of size 3x3 each.
model.add(Conv2D(32, (3, 3), activation='relu', input_shape=(100, 100, 3)))
model.add(Conv2D(32, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(256, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)


In [66]:
a = model.layers[0]
w0 = a.weights[0]
w0.shape.as_list()

[3, 3, 3, 32]

In [69]:
for i, layer in enumerate(model.layers):
    print("Layer", i+1)
    print("Name", layer.name)
    print("Input shape", layer.input_shape)
    print("Output shape", layer.output_shape)
    if not layer.weights:
        print("No weights for this layer")
    for weight in layer.weights:
        print(weight.shape.as_list())

Layer 1
Name conv2d_1
Input shape (None, 100, 100, 3)
Output shape (None, 98, 98, 32)
[3, 3, 3, 32]
[32]
Layer 2
Name conv2d_2
Input shape (None, 98, 98, 32)
Output shape (None, 96, 96, 32)
[3, 3, 32, 32]
[32]
Layer 3
Name max_pooling2d_1
Input shape (None, 96, 96, 32)
Output shape (None, 48, 48, 32)
No weights for this layer
Layer 4
Name dropout_1
Input shape (None, 48, 48, 32)
Output shape (None, 48, 48, 32)
No weights for this layer
Layer 5
Name conv2d_3
Input shape (None, 48, 48, 32)
Output shape (None, 46, 46, 64)
[3, 3, 32, 64]
[64]
Layer 6
Name conv2d_4
Input shape (None, 46, 46, 64)
Output shape (None, 44, 44, 64)
[3, 3, 64, 64]
[64]
Layer 7
Name max_pooling2d_2
Input shape (None, 44, 44, 64)
Output shape (None, 22, 22, 64)
No weights for this layer
Layer 8
Name dropout_2
Input shape (None, 22, 22, 64)
Output shape (None, 22, 22, 64)
No weights for this layer
Layer 9
Name flatten_1
Input shape (None, 22, 22, 64)
Output shape (None, 30976)
No weights for this layer
Layer 10
Name

In [70]:
model.compile(loss='categorical_crossentropy', optimizer=sgd)
model.fit(x_train, y_train, batch_size=32, epochs=10)
score = model.evaluate(x_test, y_test, batch_size=32)

Epoch 1/10
100/100 [==============================] - 7s 67ms/step - loss: 2.3410
Epoch 2/10
100/100 [==============================] - 6s 60ms/step - loss: 2.3050
Epoch 3/10
100/100 [==============================] - 5s 55ms/step - loss: 2.3193
Epoch 4/10
100/100 [==============================] - 5s 55ms/step - loss: 2.2885
Epoch 5/10
100/100 [==============================] - 5s 54ms/step - loss: 2.2776
Epoch 6/10
100/100 [==============================] - 5s 54ms/step - loss: 2.2834
Epoch 7/10
100/100 [==============================] - 6s 55ms/step - loss: 2.2705
Epoch 8/10
100/100 [==============================] - 6s 56ms/step - loss: 2.2839
Epoch 9/10
100/100 [==============================] - 5s 54ms/step - loss: 2.2871
Epoch 10/10
20/20 [==============================] - 1s 26ms/step
